ad_campaign_analytics:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT').split('.')[0] }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PROGRAMMATIC_TOKEN') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'COMPUTE_WH') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'AD_CAMPAIGNS') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'RAW') }}"
      role: "ACCOUNTADMIN"
      threads: 4
      client_session_keep_alive: true
      
    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT').split('.')[0] }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PROGRAMMATIC_TOKEN') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'COMPUTE_WH') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'AD_CAMPAIGNS') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'RAW') }}"
      role: "ACCOUNTADMIN"
      threads: 8
      client_session_keep_alive: true
